
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

PG_DATABASE_NAME = "pgdb1"

SLAVE_LIST = ("'slave1'" "'slave2'")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "centos65-x86_64-20140116"
  config.vm.box = "centos/7"
  config.vm.define "master", primary: true do |server|
    server.vm.hostname = "master.pg"
    server.vm.network "private_network", ip: "192.168.4.2"
    config.vm.network "forwarded_port", guest: 3001, host: 3002,
      auto_correct: true
    server.vm.provision "shell", path: "scripts/master.sh", args: "PG_DATABASE_NAME SLAVE_LIST"
  end

  config.vm.define "slave1" do |server|
    server.vm.hostname = "slave1.pg"
    server.vm.network "private_network", ip: "192.168.4.3"

    server.vm.provision "shell", path: "scripts/slave.sh", args: "PG_DATABASE_NAME slave1"
  end


  config.vm.define "pgbench1" do |server|
    server.vm.hostname = "pgbench1.pg"
    server.vm.network "private_network", ip: "192.168.4.15"

    server.vm.provision "shell", path: "scripts/pgbench.sh", args: "PG_DATABASE_NAME pgbench"
  end

end
